internal_domain: diesel.net
external_domain: kiwi-labs.net

# Add IP address (CIDR notation) for any proxies along the way (enables proxy chaining)
trusted_ips:
  - '{{ lookup("dig", internal_domain) }}/24' # internal CIDR
  - '{{ lookup("dig", external_domain) }}' # WAN IP

certs: []
